### ISSUE TITLE
✨ feat: 전역데이터 및 인증 상태 관리

### ISSUE THREAD

**Issue by euncherry** [DoDoDocs/dododocs-frontend#2]
# Title

- react-query를 이용한 전역 데이터 관리
- zustand를 이용한 상태관리

# TODO
- [x] Zustand를 기반으로 한 authStore 추가.
- [x] src/App.js에 React Query 클라이언트를 설정하여 전역 데이터 관리에 활용.
- [ ] 환경변수 확인  (REACT_APP_API_URL)
- [ ] 토큰이 없는 경우 에러처리

# etc

- `리팩토링 필요` QueryClient 설정 시 staleTime, retry 등의 값이 고정되어 있어 유연한 설정이 어려움.

**Comment by msung99** [comment]
와 !
